{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(request_latency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(latency_milliseconds_total[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "rate(requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizza_latency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "system_memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "user_active_count_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active User Count"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(auth_successful_logins_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_failed_logins_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "HTTP Requests/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(http_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(http_get_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(http_put_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(http_post_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(http_delete_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_revenue_1_0_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(pizza_sold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "rate(pizza_failed_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Logs Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level, time) (count_over_time({component=\"jwt-pizza-service\"}[1m]))"
    }
   ]
  }
 ]
}